### ISSUE TITLE
Gem synopsis isn't clear

### ISSUE THREAD

**Issue by EricR** [nicohvi/stump#1]
I think the synopsis of this gem is a bit unclear. Until I took a peak at source code, I thought that this was trying to provider a logger that could write to either a file or STDOUT (something of course the standard Logger class can already do). I would highlight in the README that the neat thing Stump does is provide an IO object to log to that can write to both files and STDOUT at the same time.

Showing this is in the example instead of the access log might help explain it better, too! :-)

**Comment by nicohvi** [comment]
I tried to make it a bit more clear in the `readme` now :-)
